[env]
platform = atmelsam
board = mkrzero
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit LIS3MDL@^1.2.5
    adafruit/Adafruit MAX31865 library@^1.6.2
    adafruit/Adafruit MLX90614 Library@^2.1.6

[platformio]
default_envs = all_sensors

[env:all_sensors]
build_flags = -DTEST_MAG=1 -DTEST_IR=1 -DTEST_RTD=1

[env:mag_only]
build_flags = -DTEST_MAG=1 -DTEST_IR=0 -DTEST_RTD=0

[env:ir_only]
build_flags = -DTEST_MAG=0 -DTEST_IR=1 -DTEST_RTD=0

[env:rtd_only]
build_flags = -DTEST_MAG=0 -DTEST_IR=0 -DTEST_RTD=1
