#pragma once

// Generated by tools/fit_magnetometer.py. Check kScienceReady.
namespace magcal {
inline constexpr bool kEnabled = true;
inline constexpr bool kScienceReady = false;
inline constexpr char kId[] = "BENCH_ONLY-mag3d-a08508a4ed23";
inline constexpr float kOffsetUt[3] = {-25.0111821f, 5.44491144f, 0.714632478f};
inline constexpr float kMatrix[3][3] = {
    {0.959533131f, 0.0414779335f, -0.00158204836f},
    {0.0414779335f, 0.997470417f, -0.00277374115f},
    {-0.00158204836f, -0.00277374115f, 1.00324411f}
};
}  // namespace magcal
